#!/usr/bin/env bash
# nginx installation

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
service nginx start
