#!/usr/bin/env bash

# Redirection
sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
new_config="\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n"
FILE="/etc/nginx/sites-available/default"
sudo sed -i "42i\ $new_config" "$FILE"
sudo service nginx restart
