#!/usr/bin/env bash

# Redirection
sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
FILE="/etc/nginx/sites-available/default"
sudo sed -i "42i\ $REDIRECT" "$FILE"
sudo service nginx start
