#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
FILE="/etc/nginx/sites-available/default"
ERROR="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
FILE="/etc/nginx/sites-available/default"
HEADER="\n\tadd_header X-Served-By 60552-web-01;\n\tlocation / {\n\t\tadd_header X-Served-By 60552-web-01;\n\t}\n"
sudo sed -i "47i\ $REDIRECT" "$FILE"
sudo sed -i "47i\ $ERROR" "$FILE"
sudo sed -i "47i\ $HEADER" "$FILE"
service nginx restart
