#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
FILE="/etc/nginx/sites-available/default"
HEADER="\n\tadd_header X-Served-By $hostname;\n\tlocation / {\n\t\tadd_header X-Served-By $hostname;\n\t}\n"
sudo sed -i "47i\ $HEADER" "$FILE"
service nginx restart
