#!/usr/bin/env bash
# Nginx likes port 80
sudo rm /etc/nginx/sites-enabled/default
content="server {
        listen 80 default_server;
      	root /usr/share/nginx/html;
        index index.html index.htm;
        server_name localhost;
        location / {
                try_files $uri $uri/ =404;
        }"
sudo echo "$content" > /etc/nginx/sites-enabled/default
sudo service nginx restart
