#!/usr/bin/env bash
# A script that makes use of if, elif and else
i=0
while ((i < 10));
do
	if ((i == 3)); then
		echo "bad luck"
	elif ((i == 7)); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
