#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
min=1
hour=0
while ((hour < 13)); do
	echo "Hour: $hour"
	while ((min < 60)); do
		echo $min
		((min++))
	done
	min=1
	((hour++))
done
