#!/usr/bin/env bash
# fixes a web server to run as nginx and to listen 8080 instead of 80
chmod 644 /etc/nginx/nginx.conf
sed -i '1iuser nginx' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

sudo -u nginx service nginx start
